const tintColorLight = '#2f95dc';
const tintColorDark = '#fff';

export default {
  light: {
    text: '#000',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#fff',
    background: '#000',
    tint: tintColorDark,
    tabIconDefault: '#ccc',
    tabIconSelected: tintColorDark,
  },
  primary: '#2f95dc',
  secondary: '#414757',
  error: '#f13a59',
  success: '#00B386',
  warning: '#FFC106',
  info: '#00A3FF',
  black: '#000',
  white: '#fff',
  grey: '#BEC1D2',
  lightGrey: '#E5E5E5',
  darkGrey: '#7D7D7D',
  transparent: 'transparent',
  lightBlue: '#E6F2FF',
  lightGreen: '#E6FFEC',
  lightRed: '#FFE6E6',
  lightYellow: '#FFF9E6',
  lightOrange: '#FFF2E6',
  lightPurple: '#F2E6FF',
  lightPink: '#FFE6F2',
  lightBrown: '#F5E6FF',
  lightCyan: '#E6FFFB',
  lightTeal: '#E6FFFA',
};
